project_id = "bukkfucjwayueksehgxm"

[functions.lead]
verify_jwt = false

[functions.submit-quiz]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.cartpanda-webhook]
verify_jwt = false

[functions.verify-order]
verify_jwt = false

[functions.verify-token]
verify_jwt = false

[functions.link-order]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.daily-forecast]
verify_jwt = false

[functions.daily-forecast-audio]
verify_jwt = false
